management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
spring:
  mail:
    host: smtp.gmail.com
    username:
    password:
    default-encoding: UTF-8
    protocol: smtp
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8   # 0 unlimited
        max-idle: 8     # 0 unlimited
        max-wait: -1ms  # -1 unlimited
        min-idle: 0     # 0 unlimited
      shutdown-timeout: 100ms
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password:
        allow:
    dynamic:
      p6spy: false
      lazy: false
      # druid configuration
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: SELECT 1 FROM DUAL
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/ai-stock?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        slave_1:
          url: jdbc:mysql://localhost:3306/ai-stock?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #设置自动启动，默认为 true
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 15
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  #rabbitmqp配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false
    listener:
      simple:
        acknowledge-mode: auto
    virtual-host: s-boot-prod
knife4j:
  enable: true
  production: true
logging:
  level:
    com.baomidou: info
config:
  shiro:
    exclude: /api/**
mybatis-plus:
  mapper-locations: classpath:**/*Mapper.xml
minio:
  url: http://***.com:9090
  accessKey:
  secretKey:
