spring:
  profiles:
    active: dev
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: manage-system
  mail:
    host: smtp.gmail.com
    username: test@gmail.com
    password: ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 9990
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /s-boot
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*,application/vnd.ms-excel
